spring:
  rabbitmq:
    host: 121.40.160.237
    port: 5672
    username: admin
    password: 123
    virtual-host: /
    publisher-confirm-type: correlated #发布确认模式
    publisher-returns: true #回退消息


server:
  port: 8080
